version: '3.7'

services:
###################################################################################################
#                                           SETUP                                                 #
###################################################################################################

  # El servicio de 'configuración' ejecuta un script único que inicializa los
  # usuarios 'logstash_internal' y 'kibana_system' dentro de Elasticsearch
  # con los valores de las contraseñas definidas en el archivo '.env'.

  # Esta tarea solo se realiza durante el inicio *inicial* de la pila. En todas
  # las ejecuciones posteriores, el servicio simplemente regresa de 
  # inmediato, sin realizar ninguna modificación a los usuarios existentes.

  setup:
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    ### VOLUMENES
    volumes:
      - ./setup/state:/state
      # - setup:/state:Z
    container_name: setup
    ### VARIABLES DE ENTORNO
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    ### NETWORK
    networks:
      - urge-network
    depends_on:
      - elasticsearch

###################################################################################################
#                                       ELASTIC SEARCH                                            #
###################################################################################################
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    ### VOLUMENES
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      # - elasticsearch:/usr/share/elasticsearch/data:ro,Z
    container_name: elasticsearch
    ### PUERTOS
    ports:
      - "9200:9200"
      - "9300:9300"
    ### VARIABLES DE ENTORNO
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Contraseña de arranque.
      # Se utiliza para inicializar el almacén de claves durante el inicio inicial
      # de Elasticsearch. Ignorado en ejecuciones posteriores.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Se utiliza "single-node" en el "discovery.type" para que el nodo 
      # se elija a sí mismo como maestro y no se unirá a un clúster con ningún otro nodo.
      # Referencia: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    ### NETWORK
    networks:
      - urge-network

###################################################################################################
#                                         LOGSTASH                                                #
###################################################################################################
  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    ### VOLUMENES
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    container_name: logstash
    ### PUERTOS
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    ### VARIABLES DE ENTORNO
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    ### NETWORK
    networks:
      - urge-network
    depends_on:
      - elasticsearch

###################################################################################################
#                                          KIBANA                                                 #
###################################################################################################
  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    ### VOLUMENES
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    container_name: kibana
    ### PUERTOS
    ports:
      - "5601:5601"
    ### VARIABLES DE ENTORNO
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    ### NETWORK
    networks:
      - urge-network
    depends_on:
      - elasticsearch

### DOCKER NETWORK
networks:
  urge-network:
   external: true 

### DOCKER VOLUMES
# volumes:
#   setup:
#   elasticsearch:
